### ISSUE TITLE
Flickity not working with Elementor

### ISSUE THREAD

**Issue by wayheming** [metafizzy/flickity#861]
Hello, I am faced with the same problem is there a solution?
#491

**Comment by wayheming** [comment]
@desandro I looked at your code and in my situation this condition works and the elements are not found if I comment on the part of the code everything works well

`utils.filterFindElements() method`

`// check that elem is an actual element`
`if (!(elem instanceof HTMLElement)) {`
     `return;`
`}
`

http://prntscr.com/lg7tf8

What do you think about it? thx

**Comment by wayheming** [comment]
@desandro I tried to add a little to your check. What do you think of this?

```
// ----- filterFindElements ----- //

	utils.filterFindElements = function (elems, selector) {
		// make array of elems
		elems = utils.makeArray(elems);
		var ffElems = [];

		var isElement = function (elem) {
			return (
				typeof HTMLElement === "object" ? elem instanceof HTMLElement : elem && typeof elem === "object" && elem !== null && elem.nodeType === 1 && typeof elem.nodeName === "string"
			);
		};

		elems.forEach(function (elem) {
			// check that elem is an actual element
			if (!isElement(elem)) {
				return;
			}
			// add elem if no selector
			if (!selector) {
				ffElems.push(elem);
				return;
			}
			// filter & find items if we have a selector
			// filter
			if (matchesSelector(elem, selector)) {
				ffElems.push(elem);
			}
			// find children
			var childElems = elem.querySelectorAll(selector);
			// concat childElems to filterFound array
			for (var i = 0; i < childElems.length; i++) {
				ffElems.push(childElems[i]);
			}
		});

		return ffElems;
	};

```

**Comment by desandro** [comment]
I'm sorry to see you're having trouble with Flickity. Could you provide a **reduced test case**? See [Submitting Issues in the contributing guidelines](https://github.com/metafizzy/flickity/blob/master/.github/contributing.md#submitting-issues).

**Comment by wayheming** [comment]
@desandro Thanks for your answer, but the problem is that I cannot reproduce the problem on CodePen. I work locally, the problem is in my WordPress theme with the plugin Elementor. There are too many dependencies to reproduce to you on CodePen. Could you look at the code that I showed and evaluate this part does where I found the problem? 

```
if (!(elem instanceof HTMLElement)) {
```

**Comment by wayheming** [comment]
@desandro I managed to reproduce the problem https://jsfiddle.net/wayheming/xpvt214o/936582/

**Comment by desandro** [comment]
Looks like you're creating an iframe. As that iframe is its own sandbox, it will need the Flickity JS and CSS added to it.

**Comment by wayheming** [comment]
I added a style and script inside 123 but the problem remains can you see?https://jsfiddle.net/wayheming/xpvt214o/943640/

**Comment by wayheming** [comment]
@desandro 
I added a style and script inside 123 but the problem remains can you see?https://jsfiddle.net/wayheming/xpvt214o/943640/

**Comment by desandro** [comment]
I think we're running into a bigger issue. iframes are designed to be isolated sandboxes, so I'm not sure if you can initialize JS functionality in an iframe from outside of it. Additionally, the iframe would need CSS for `.carousel` and perhaps jQuery JS

**Comment by wayheming** [comment]
@desandro but when I modify the function `filterFindElements` as I showed above, the problem is solved

**Comment by desandro** [comment]
The best way for me to debug this issue is to look at a working **reduced test case** that demonstrates the problem.

**Comment by desandro** [comment]
If you can create a reduced test case that uses Elementor that'd be helpful.

**Comment by iamntz** [comment]
@desandro this is an old issue, and despite being closed, is still present. Unfortunately there is no easy way to make it reproductible, as it's tied to Elementor, _but_ as other mentioned, the issue seems to be on this piece:

```
    if ( !( elem instanceof HTMLElement ) ) {
      console.log(elem.constructor.name, elem instanceof HTMLElement);
      // return;
    }
```

Sometimes the `instanceof` fails:

```
HTMLDivElement false
HTMLDivElement true
```

This will mess up the whole markup(either by having the viewport element appended at the very end, or by having only some elements in the viewport). Finally, _sometimes_ the markup is build correctly, but it's SO erratic that can't be replicated reliably.

I also tried to enable flickity slightly delayed and on a user interaction (the initial idea was that there are some images not loaded completely) but with no luck.

Most likely, Elementor is injecting some code that it's not detected properly by Flickity, which causes all sort of weird behavior.

**Comment by drybx** [comment]
Is there still no proper fix for that?
